language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      python: 3.6.2
      sudo: false
      env: CC_COMPILER=gcc CXX_COMPILER=g++

script:
  - cmake --version
  - $CC_COMPILER -v
  - $CXX_COMPILER -v
  - python3 --version
  - python --version
  - mkdir build
  - cd build
  - cmake ..
  - make


env:
  global:
  - LANG="en_US.UTF-8"
